/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountLinkToUi: typeof import('./src/components/panel/accountSubComponents/AccountLinkToUi.vue')['default']
    AccountPanel: typeof import('./src/components/panel/AccountPanel.vue')['default']
    AccountShopLinkMessage: typeof import('./src/components/panel/accountSubComponents/AccountShopLinkMessage.vue')['default']
    BaseOverlay: typeof import('./src/components/BaseOverlay.vue')['default']
    ModuleUpdateInformationAlert: typeof import('./src/components/alert/ModuleUpdateInformationAlert.vue')['default']
    PsAccountComponentAlertDisplay: typeof import('./src/components/containers/PsAccountComponentAlertDisplay.vue')['default']
    PsAccounts: typeof import('./src/components/PsAccounts.vue')['default']
    PuikAlert: typeof import('@prestashopcorp/puik/es')['PuikAlert']
    PuikCard: typeof import('@prestashopcorp/puik/es')['PuikCard']
    PuikLink: typeof import('@prestashopcorp/puik/es')['PuikLink']
    ShopUrlShouldExistsAlert: typeof import('./src/components/alert/ShopUrlShouldExistsAlert.vue')['default']
    UserEmailNotValidatedAlert: typeof import('./src/components/alert/UserEmailNotValidatedAlert.vue')['default']
    UserNotSuperAdminAlert: typeof import('./src/components/alert/UserNotSuperAdminAlert.vue')['default']
  }
}
