preserve_hierarchy: true
commit_message: "[ci skip] fix: New (%language%) translations"
append_commit_message: false
pull_request_labels:
  - translations
files:
  - source: /src/locale/lang/en.json
    dest: /psaccounts/vue-components.json
    translation: /src/locale/lang/%two_letters_code%.json
    type: json
    labels:
      - psaccounts
      - vue-components
