project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: '/src/locale/lang/en.json'
    dest:   '/psaccounts/vue-components.json'
    translation: '/src/locale/lang/%two_letters_code%.json'
    type: 'json'
    labels:
      - 'psaccounts'
      - 'vue-components'
