/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountLinkToUi: typeof import('./../components/panel/accountSubComponents/AccountLinkToUi.vue')['default']
    AccountPanel: typeof import('./../components/panel/AccountPanel.vue')['default']
    AccountShopLinkMessage: typeof import('./../components/panel/accountSubComponents/AccountShopLinkMessage.vue')['default']
    AlertContextValidator: typeof import('./../components/alert/AlertContextValidator.vue')['default']
    AlertModuleDependencies: typeof import('./../components/alert/AlertModuleDependencies.vue')['default']
    AlertModuleUpdateInformation: typeof import('./../components/alert/AlertModuleUpdateInformation.vue')['default']
    AlertShopUnlinked: typeof import('./../components/alert/AlertShopUnlinked.vue')['default']
    AlertShopUrlShouldExists: typeof import('./../components/alert/AlertShopUrlShouldExists.vue')['default']
    AlertUpdateToLatest: typeof import('./../components/alert/AlertUpdateToLatest.vue')['default']
    AlertUserNotSuperAdmin: typeof import('./../components/alert/AlertUserNotSuperAdmin.vue')['default']
    BaseOverlay: typeof import('./../components/common/BaseOverlay.vue')['default']
    InvitationBanner: typeof import('./../components/invitation/InvitationBanner.vue')['default']
    PsAccounts: typeof import('./../components/PsAccounts.vue')['default']
    PuikAlert: typeof import('@prestashopcorp/puik/es')['PuikAlert']
    PuikButton: typeof import('@prestashopcorp/puik/es')['PuikButton']
    PuikCard: typeof import('@prestashopcorp/puik/es')['PuikCard']
    PuikIcon: typeof import('@prestashopcorp/puik/es')['PuikIcon']
    PuikLink: typeof import('@prestashopcorp/puik/es')['PuikLink']
  }
}
