/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountLinkToUi: typeof import('./../components/panel/accountSubComponents/AccountLinkToUi.vue')['default']
    AccountPanel: typeof import('./../components/panel/AccountPanel.vue')['default']
    AccountShopLinkMessage: typeof import('./../components/panel/accountSubComponents/AccountShopLinkMessage.vue')['default']
    BaseAlert: typeof import('./../components/alert/BaseAlert.vue')['default']
    BaseButton: typeof import('./../components/BaseButton.vue')['default']
    BaseCard: typeof import('./../components/BaseCard.vue')['default']
    BaseDropdown: typeof import('./../components/BaseDropdown.vue')['default']
    BaseDropdownItemButton: typeof import('./../components/BaseDropdownItemButton.vue')['default']
    BaseOverlay: typeof import('./../components/BaseOverlay.vue')['default']
    ContextValidatorAlert: typeof import('./../components/alert/ContextValidatorAlert.vue')['default']
    ModuleDependenciesAlert: typeof import('./../components/alert/ModuleDependenciesAlert.vue')['default']
    ModuleUpdateInformationAlert: typeof import('./../components/alert/ModuleUpdateInformationAlert.vue')['default']
    PsAccounts: typeof import('./../components/PsAccounts.vue')['default']
    PuikAlert: typeof import('@prestashopcorp/puik/es')['PuikAlert']
    PuikButton: typeof import('@prestashopcorp/puik/es')['PuikButton']
    PuikCard: typeof import('@prestashopcorp/puik/es')['PuikCard']
    PuikLink: typeof import('@prestashopcorp/puik/es')['PuikLink']
    ShopUrlShouldExistsAlert: typeof import('./../components/alert/ShopUrlShouldExistsAlert.vue')['default']
    UserNotSuperAdminAlert: typeof import('./../components/alert/UserNotSuperAdminAlert.vue')['default']
  }
}
