name: Accounts CI/CD

on:
  pull_request:
    types: [opened,edited,reopened,synchronize,labeled]

jobs:
  alpha:
    name: Alpha - Storybook
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: contains(github.event.pull_request.labels.*.name, 'quality assurance needed')

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Gcloud auth and write env file
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS > token.json
          gcloud auth activate-service-account --key-file=token.json
          gcloud container clusters get-credentials $GCLOUD_CLUSTER \
          --zone europe-west1-c --project distribution-integration
          gcloud auth configure-docker
          rm token.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}
          GCLOUD_CLUSTER: ${{ secrets.INTEGRATION_GCLOUD_CLUSTER }}

      - name: Terraform init
        working-directory: cloud
        run: |
          terraform init
          terraform workspace select alpha
          terraform fmt
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Docker pull
        continue-on-error: true
        run: docker pull "eu.gcr.io/distribution-integration/accounts-vue-components-package:latest"

      - name: Build package
        run: |
          docker build \
            --target=package \
            --cache-from="eu.gcr.io/distribution-integration/accounts-vue-components-package:latest" \
            --tag="eu.gcr.io/distribution-integration/accounts-vue-components-package:latest" .
          docker push "eu.gcr.io/distribution-integration/accounts-vue-components-package:latest"

      - name: Build and push finale image
        run: |
          docker build . \
            --tag="eu.gcr.io/distribution-integration/accounts-vue-components:latest" \
            --cache-from="eu.gcr.io/distribution-integration/accounts-vue-components-package:latest"
          docker push "eu.gcr.io/distribution-integration/accounts-vue-components:latest"
        env:
          TAG: ${{ steps.get_tag.outputs.TAG }}

      - name: Terraform apply
        working-directory: cloud
        run: terraform apply -auto-approve
        env:
          SHA: ${{ github.sha }}
          GOOGLE_CREDENTIALS: ${{ secrets.INTEGRATION_GOOGLE_APPLICATION_CREDENTIALS }}
