name: Sync translations

on:
  push:
    branches: [ master, feat/** ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: |
        echo BRANCH=${GITHUB_REF#refs/heads/} >> $GITHUB_ENV
        echo CROWDIN_BRANCH=$(echo "$GITHUB_REF" | sed -e 's/refs\/heads\///' -e 's/\//./g') >> $GITHUB_ENV

    - name: Crowdin action
      uses: crowdin/github-action@1.1.0
      with:
        download_translations: true
        localization_branch_name: l10n/${{ env.BRANCH }}
        pull_request_title: New Crowdin translations for ${{ env.BRANCH }} branch
        pull_request_base_branch_name: ${{ env.BRANCH }}
        crowdin_branch_name: ${{ env.CROWDIN_BRANCH }}
        config: crowdin.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
