name: Crowdin Action

on:
  push:
    branches: [ master, integration, 'feature/**' ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: |
        echo BRANCH=${GITHUB_REF#refs/heads/} >> $GITHUB_ENV
        echo CROWDIN_BRANCH=$(echo "$GITHUB_REF" | sed -e 's/refs\/heads\///' -e 's/\//./g') >> $GITHUB_ENV
      id: extract_branch

    - name: Crowdin action
      uses: crowdin/github-action@1.1.0
      with:
        download_translations: true
        commit_message: New Crowdin translations for ${{ env.BRANCH }} branch
        localization_branch_name: l10n/${{ env.BRANCH }}
        pull_request_title: New Crowdin translations for ${{ env.BRANCH }} branch
        pull_request_base_branch_name: ${{ env.BRANCH }}
        crowdin_branch_name: ${{ env.CROWDIN_BRANCH }}
        config: crowdin.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: 459732
        CROWDIN_PERSONAL_TOKEN: 79c49a29a6494ec4704900eb6c51b5381bc2f9a9679e4e9b306c5560655cbc8ec8798428cfa06f76
